application: weather-beacon
version: 7
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /admin/.*
  script: weatherbeacon.application
  login: admin
- url: /v0/.*
  script: weatherbeacon.application
- url: /
  script: weatherbeacon.application
- url: /
  static_dir: static


libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest
- name: webapp2
  version: latest
- name: yaml
  version: latest
